name: "Project setup"
description: "This actions will setup Python, the cache and install the dependencies"
author: "Mathieu Tarral"
inputs:
  python_version:
    description: "Python version to setup"
    required: true
    default: "3.13"
  poetry_version:
    description: "Poetry version to setup"
    required: true
    default: "2.1.3"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  - name: Install poetry
    run: pipx install poetry
    shell: bash

  - name: Set up Python ðŸ
    id: setup-python
    uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    with:
      python-version: ${{ inputs.python_version }}
      cache: 'poetry'

  - name: Default shell
    run: |
      if [ "$RUNNER_OS" == "Linux" ]; then
            echo shellos=bash >> $GITHUB_ENV
      elif [ "$RUNNER_OS" == "Windows" ]; then
            echo shellos=powershell >> $GITHUB_ENV
      else
            echo "$RUNNER_OS not supported"
            exit 1
      fi
    shell: bash

  # The 'setup-python' action with 'cache: poetry' installs dependencies but not the project
  # itself. This step installs the project package into the created virtual environment.
  - name: Install project
    run: poetry install
    shell: ${{ env.shellos }}
