name: "Project setup"
description: "This actions will setup Python, the cache and install the dependencies"
author: "Mathieu Tarral"
inputs:
  python_version:
    description: "Python version to setup"
    required: true
    default: "3.13"
  poetry_version:
    description: "Poetry version to setup"
    required: true
    default: "2.1.3"
runs:
  using: "composite"
  steps:
  - name: Set up Python 🐍
    id: setup-python
    uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    with:
      python-version: ${{ inputs.python_version }}

  - name: Install poetry
    uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0

  - name: Setup a local virtual environment (if no poetry.toml file)
    run: |
      poetry config virtualenvs.create true --local
      poetry config virtualenvs.in-project true --local
    shell: bash

  - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    name: Define a cache for the virtual environment based on the dependencies lock file
    with:
      path: ./.venv
      key: venv-${{ hashFiles('poetry.lock') }}

  - name: Set Poetry environment
    run: poetry env use ${{ inputs.python_version }}
    shell: bash

  - name: Default shell
    run: |
      if [ "$RUNNER_OS" == "Linux" ]; then
            echo shellos=bash >> $GITHUB_ENV
      elif [ "$RUNNER_OS" == "Windows" ]; then
            echo shellos=powershell >> $GITHUB_ENV
      else
            echo "$RUNNER_OS not supported"
            exit 1
      fi
    shell: bash

  # The 'setup-python' action with 'cache: poetry' installs dependencies but not the project
  # itself. This step installs the project package into the created virtual environment.
  - name: Install project
    run: poetry install
    shell: ${{ env.shellos }}
